// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdkDnUJ0wvT4IbKZW6IiiZ2JD9vj2BvJU',
    appId: '1:588917733063:web:6eb785d65086cc67e8b0e2',
    messagingSenderId: '588917733063',
    projectId: 'flutter-chat-c70f4',
    authDomain: 'flutter-chat-c70f4.firebaseapp.com',
    storageBucket: 'flutter-chat-c70f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXrbxxFSGad9EIS72ybP9FCeW8iAu4L2Y',
    appId: '1:588917733063:android:a4441d349013174ee8b0e2',
    messagingSenderId: '588917733063',
    projectId: 'flutter-chat-c70f4',
    storageBucket: 'flutter-chat-c70f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlJznde-E-5RO0B0l0709qlKLo4rUYMOA',
    appId: '1:588917733063:ios:66666bfa5b0410f2e8b0e2',
    messagingSenderId: '588917733063',
    projectId: 'flutter-chat-c70f4',
    storageBucket: 'flutter-chat-c70f4.appspot.com',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdkDnUJ0wvT4IbKZW6IiiZ2JD9vj2BvJU',
    appId: '1:588917733063:web:5dd580134bf46b30e8b0e2',
    messagingSenderId: '588917733063',
    projectId: 'flutter-chat-c70f4',
    authDomain: 'flutter-chat-c70f4.firebaseapp.com',
    storageBucket: 'flutter-chat-c70f4.appspot.com',
  );
}
